import {
  FLOOR_2_RUGS,
  FLOOR_2_WALL_DECOR,
  FLOOR_2_ZONE_FLOOR,
  MAP_HEIGHT,
  MAP_WIDTH,
  glyphAt,
  zoneAt,
  type FloorId,
  type ZoneId,
} from '@/content/office'
import { TILE_ATLAS, TILE_PAD, TILE_STRIDE_X, TILE_STRIDE_Y, type TileName } from './tileAtlas'

/* ─── Office tileset (Floors 1 and 2) ────────────────────────
   Hand-authored pixel art in public/office/tiles.png (generated by
   scripts/gen_office_tiles.py). This module only decides which atlas cell
   goes where; WorldMap paints the result as sprite-sheet spans. Floor 2's
   glyph legend is docs/rpg/floor-2-design.md §1.2.

   Two passes:
   - floor: zone floor / rug, wall autotile (16 masks), wall shadows onto
     the floor, doorway frames, wall-face decor. Static.
   - props: everything with a footprint. Cells are 32×48 and overflow 16px
     upward, so props are z-sorted by row together with the actors. */

export interface TileStates {
  printer: 'error' | 'working' | 'printing'
  cabinetOpen: boolean
  counterSteaming: boolean
  vendingLit: boolean
  readerGreen: boolean
  elevatorOpen: boolean
  // Floor 2 (design §10.3)
  boothFlash?: boolean
  badgePrinter?: 'idle' | 'printing' | 'done'
  shredding?: boolean
}

/** One sprite-sheet cell placed at a tile. `frames` > 1 steps through neighbours. */
export interface Sprite {
  name: TileName
  frames?: number
  periodMs?: number
}

export interface FloorCell {
  x: number
  y: number
  layers: Sprite[]
}

export interface PropCell {
  x: number
  y: number
  sprite: Sprite
}

const FLOOR_FOR_ZONE: Record<ZoneId, TileName> = {
  zone_hall: 'floor_hall',
  zone_reception: 'floor_reception',
  zone_desks: 'floor_desks',
  zone_break: 'floor_break',
  zone_meeting: 'floor_meeting',
  zone_elevator: 'floor_elevator',
  ...(FLOOR_2_ZONE_FLOOR as Record<keyof typeof FLOOR_2_ZONE_FLOOR, TileName>),
}

/** Rugs are presentation only: rectangles of floor that get a 9-patch. */
type Rug = { x0: number; y0: number; x1: number; y1: number; kind: 'red' | 'gold' | 'navy' }
const RUGS: Record<FloorId, Rug[]> = {
  floor_01: [
    { x0: 2, y0: 2, x1: 4, y1: 3, kind: 'red' }, // in front of the elevator
    { x0: 6, y0: 13, x1: 10, y1: 14, kind: 'gold' }, // behind the reception counter
    { x0: 12, y0: 1, x1: 12, y1: 12, kind: 'navy' }, // hall runner down the spine
  ],
  floor_02: FLOOR_2_RUGS,
}

/** Wall-face decor keyed by `x,y` of the wall tile it hangs on. */
const WALL_DECOR_F1: Record<string, TileName> = {
  // elevator lobby, north wall
  '1,0': 'vent',
  '5,0': 'clock',
  '6,0': 'window_l',
  '7,0': 'window_r',
  '9,0': 'extinguisher',
  // meeting room, north wall
  '15,0': 'sign_meeting',
  '16,0': 'whiteboard_l',
  '17,0': 'whiteboard_r',
  '19,0': 'window_l',
  '20,0': 'window_r',
  '22,0': 'vent',
  // desks, north wall
  '2,6': 'pinboard',
  '4,6': 'clock',
  '6,6': 'poster',
  '8,6': 'extinguisher',
  // break room, north wall
  '15,6': 'sign_kitchen',
  '16,6': 'menu_l',
  '17,6': 'menu_r',
  '21,6': 'shelf_mugs',
  '22,6': 'vent',
  // reception, north wall
  '2,12': 'extinguisher',
  '7,12': 'logo_l',
  '8,12': 'logo_m',
  '9,12': 'logo_r',
  '15,12': 'clock',
  '17,12': 'poster',
  '19,12': 'pinboard',
  '21,12': 'vent',
}

const WALL_DECOR: Record<FloorId, Record<string, TileName>> = {
  floor_01: WALL_DECOR_F1,
  floor_02: FLOOR_2_WALL_DECOR as Record<string, TileName>,
}

function isWall(g: string) {
  return g === '#'
}

function isWalkable(g: string) {
  return g === '.' || g === 'D' || /[1-4]/.test(g)
}

/** Wall autotile mask: bit set when that neighbour is open (not wall). N=1 E=2 S=4 W=8. */
export function wallMask(tx: number, ty: number, floorId: FloorId = 'floor_01'): number {
  return (
    (isWall(glyphAt(tx, ty - 1, floorId)) ? 0 : 1) |
    (isWall(glyphAt(tx + 1, ty, floorId)) ? 0 : 2) |
    (isWall(glyphAt(tx, ty + 1, floorId)) ? 0 : 4) |
    (isWall(glyphAt(tx - 1, ty, floorId)) ? 0 : 8)
  )
}

/** A wall shows its plaster face when the tile south of it is open. */
export function wallShowsFace(tx: number, ty: number, floorId: FloorId = 'floor_01'): boolean {
  return (wallMask(tx, ty, floorId) & 4) !== 0
}

function rugPart(x: number, y: number, floorId: FloorId): TileName | null {
  for (const r of RUGS[floorId]) {
    if (x < r.x0 || x > r.x1 || y < r.y0 || y > r.y1) continue
    // A one-row runner is `tb`; a one-column runner is `lr`.
    const v = r.y0 === r.y1 ? 'tb' : y === r.y0 ? 't' : y === r.y1 ? 'b' : ''
    const h = r.x0 === r.x1 ? 'lr' : x === r.x0 ? 'l' : x === r.x1 ? 'r' : ''
    const part = `${v}${h}` || 'c'
    return `rug_${r.kind}_${part}` as TileName
  }
  return null
}

/** Doorway frame for a `D` tile: stacked openings in a vertical wall read as
 *  one retracted glass partition (top / mid / bot); a lone opening with wall
 *  above and below is a single partition; a door in a horizontal wall gets a
 *  header. */
export function doorSprite(tx: number, ty: number, floorId: FloorId = 'floor_01'): TileName {
  const n = isWall(glyphAt(tx, ty - 1, floorId))
  const s = isWall(glyphAt(tx, ty + 1, floorId))
  const w = isWall(glyphAt(tx - 1, ty, floorId))
  const e = isWall(glyphAt(tx + 1, ty, floorId))
  if ((w || e) && !n && !s) return 'door_h'
  if (n && s) return 'door_v_single'
  if (n) return 'door_v_top'
  if (s) return 'door_v_bot'
  return 'door_v_mid'
}

export function floorSprites(tx: number, ty: number, floorId: FloorId = 'floor_01'): Sprite[] {
  const g = glyphAt(tx, ty, floorId)
  const out: Sprite[] = []
  if (isWall(g) || g === 'X') {
    out.push({ name: `wall_${wallMask(tx, ty, floorId)}` as TileName })
    if (g === 'X') out.push({ name: 'street_exit' })
    const decor = WALL_DECOR[floorId][`${tx},${ty}`]
    if (decor && wallShowsFace(tx, ty, floorId)) out.push({ name: decor })
    return out
  }
  out.push({ name: rugPart(tx, ty, floorId) ?? FLOOR_FOR_ZONE[zoneAt(tx, ty, floorId)] })
  if (isWall(glyphAt(tx, ty - 1, floorId))) out.push({ name: 'shade_n' })
  if (isWall(glyphAt(tx - 1, ty, floorId))) out.push({ name: 'shade_w' })
  if (g === 'D') out.push({ name: doorSprite(tx, ty, floorId) })
  return out
}

/** The static floor pass for the whole map. */
export function floorCells(floorId: FloorId = 'floor_01'): FloorCell[] {
  const cells: FloorCell[] = []
  for (let y = 0; y < MAP_HEIGHT; y++) {
    for (let x = 0; x < MAP_WIDTH; x++) cells.push({ x, y, layers: floorSprites(x, y, floorId) })
  }
  return cells
}

const isTable = (g: string) => g === 'T' || g === 'A'
const isDesk = (g: string) => g === '=' || g === 'd'

export function propSprite(
  tx: number,
  ty: number,
  s: TileStates,
  floorId: FloorId = 'floor_01',
): Sprite | null {
  const g = glyphAt(tx, ty, floorId)
  switch (g) {
    case '=': {
      const left = glyphAt(tx - 1, ty, floorId) === '='
      const right = glyphAt(tx + 1, ty, floorId) === '='
      const part = left && right ? 'm' : left ? 'r' : 'l'
      if (ty === 15) return { name: `rdesk_${part}` as TileName }
      if (part === 'r') return { name: 'desk_r' }
      return { name: `desk_${part}_0` as TileName, frames: 2, periodMs: 2600 }
    }
    case 'c': {
      const north = glyphAt(tx, ty - 1, floorId)
      return { name: isDesk(north) || isTable(north) ? 'chair_n' : 'chair_s' }
    }
    case 'P':
      if (s.printer === 'printing') return { name: 'printer_printing_0', frames: 2, periodMs: 700 }
      return { name: s.printer === 'error' ? 'printer_error' : 'printer_working' }
    case 'S':
      return { name: s.cabinetOpen ? 'cabinet_open' : 'cabinet_closed' }
    case 'K': {
      const left = glyphAt(tx - 1, ty, floorId) === 'K'
      const right = glyphAt(tx + 1, ty, floorId) === 'K'
      if (!left) {
        return s.counterSteaming
          ? { name: 'counter_steam_0', frames: 2, periodMs: 1000 }
          : { name: 'counter_machine' }
      }
      return { name: right ? 'counter_cups' : 'counter_sink' }
    }
    case 'V':
      return s.vendingLit
        ? { name: 'vending_lit_0', frames: 2, periodMs: 640 }
        : { name: 'vending_idle' }
    case 't': {
      const right = glyphAt(tx - 1, ty, floorId) === 't'
      if (floorId === 'floor_02') return { name: right ? 'btable_f2_r' : 'btable_f2_l' }
      return { name: right ? 'btable_r' : 'btable_l' }
    }
    case 'T':
    case 'A': {
      const top = !isTable(glyphAt(tx, ty - 1, floorId))
      const left = !isTable(glyphAt(tx - 1, ty, floorId))
      const right = !isTable(glyphAt(tx + 1, ty, floorId))
      const part = `${top ? 't' : 'b'}${left ? 'l' : right ? 'r' : ''}`
      if (g === 'A' && part === 'tl') return { name: 'mtable_tl_agenda' }
      return { name: `mtable_${part}` as TileName }
    }
    case 'H':
      return { name: 'handout_rack' }
    case 'w':
      return { name: 'water_cooler' }
    case 'i':
      return { name: floorId === 'floor_02' ? 'directory_f2' : 'directory' }
    case 'p':
      return { name: (tx + ty) % 2 ? 'plant_b' : 'plant_a' }
    case 'E': {
      const side = glyphAt(tx - 1, ty, floorId) === 'E' ? 'r' : 'l'
      return { name: `elev_${side}_${s.elevatorOpen ? 'open' : 'closed'}` as TileName }
    }
    case 'R':
      return {
        name: s.readerGreen ? 'reader_green_0' : 'reader_red_0',
        frames: 2,
        periodMs: 1300,
      }
    // ── Floor 2 props (design §1.2) ──
    case 'B':
      return s.boothFlash
        ? { name: 'photo_booth_flash_0', frames: 2, periodMs: 220 }
        : { name: 'photo_booth_idle' }
    case 'b':
      if (s.badgePrinter === 'printing')
        return { name: 'badge_printer_printing_0', frames: 2, periodMs: 600 }
      return { name: s.badgePrinter === 'done' ? 'badge_printer_done' : 'badge_printer_idle' }
    case 'G':
      return { name: 'server_rack_0', frames: 2, periodMs: 900 }
    case 'f':
      return { name: tx % 2 ? 'filing_open' : 'filing_closed' }
    case 'Q': {
      const left = glyphAt(tx - 1, ty, floorId) === 'Q'
      const right = glyphAt(tx + 1, ty, floorId) === 'Q'
      return { name: `pcounter_${left && right ? 'm' : left ? 'r' : 'l'}` as TileName }
    }
    case 'L':
      return { name: glyphAt(tx - 1, ty, floorId) === 'L' ? 'sofa_r' : 'sofa_l' }
    case 'd':
      return { name: glyphAt(tx - 1, ty, floorId) === 'd' ? 'exec_desk_r' : 'exec_desk_l' }
    case 'k':
      return { name: 'locker' }
    case 'j':
      return { name: 'janitor_cart' }
    case '$':
      return { name: 'safe' }
    case 'm':
      return s.shredding
        ? { name: 'shredder_shredding_0', frames: 2, periodMs: 500 }
        : { name: 'shredder_idle' }
    default:
      return null
  }
}

/** Every prop on the floor for the given states. */
export function propCells(s: TileStates, floorId: FloorId = 'floor_01'): PropCell[] {
  const cells: PropCell[] = []
  for (let y = 0; y < MAP_HEIGHT; y++) {
    for (let x = 0; x < MAP_WIDTH; x++) {
      const sprite = propSprite(x, y, s, floorId)
      if (sprite) cells.push({ x, y, sprite })
    }
  }
  return cells
}

/** Sheet offset of an atlas cell's art (inside its extruded slot), as CSS background-position. */
export function atlasOffset(name: TileName): { bx: number; by: number } {
  const [col, row] = TILE_ATLAS[name]
  return { bx: -(col * TILE_STRIDE_X + TILE_PAD), by: -(row * TILE_STRIDE_Y + TILE_PAD) }
}

export { isWalkable }
