import { MAP_HEIGHT, MAP_WIDTH, glyphAt, zoneAt, type ZoneId } from '@/content/office'
import { TILE_ATLAS, type TileName } from './tileAtlas'

/* ─── Floor 1 tileset ────────────────────────────────────────
   Hand-authored pixel art in public/office/tiles.png (generated by
   scripts/gen_office_tiles.py). This module only decides which atlas cell
   goes where; WorldMap paints the result as sprite-sheet spans.

   Two passes:
   - floor: zone floor / rug, wall autotile (16 masks), wall shadows onto
     the floor, doorway frames, wall-face decor. Static.
   - props: everything with a footprint. Cells are 32×48 and overflow 16px
     upward, so props are z-sorted by row together with the actors. */

export interface TileStates {
  printer: 'error' | 'working' | 'printing'
  cabinetOpen: boolean
  counterSteaming: boolean
  vendingLit: boolean
  readerGreen: boolean
  elevatorOpen: boolean
}

/** One sprite-sheet cell placed at a tile. `frames` > 1 steps through neighbours. */
export interface Sprite {
  name: TileName
  frames?: number
  periodMs?: number
}

export interface FloorCell {
  x: number
  y: number
  layers: Sprite[]
}

export interface PropCell {
  x: number
  y: number
  sprite: Sprite
}

const FLOOR_FOR_ZONE: Record<ZoneId, TileName> = {
  zone_hall: 'floor_hall',
  zone_reception: 'floor_reception',
  zone_desks: 'floor_desks',
  zone_break: 'floor_break',
  zone_meeting: 'floor_meeting',
  zone_elevator: 'floor_elevator',
}

/** Rugs are presentation only: rectangles of floor that get a 9-patch. */
const RUGS: { x0: number; y0: number; x1: number; y1: number; kind: 'red' | 'gold' | 'navy' }[] = [
  { x0: 2, y0: 2, x1: 4, y1: 3, kind: 'red' }, // in front of the elevator
  { x0: 6, y0: 13, x1: 10, y1: 14, kind: 'gold' }, // behind the reception counter
  { x0: 12, y0: 1, x1: 12, y1: 12, kind: 'navy' }, // hall runner down the spine
]

/** Wall-face decor keyed by `x,y` of the wall tile it hangs on. */
const WALL_DECOR: Record<string, TileName> = {
  // elevator lobby, north wall
  '1,0': 'vent',
  '5,0': 'clock',
  '6,0': 'window_l',
  '7,0': 'window_r',
  '9,0': 'extinguisher',
  // meeting room, north wall
  '15,0': 'sign_meeting',
  '16,0': 'whiteboard_l',
  '17,0': 'whiteboard_r',
  '19,0': 'window_l',
  '20,0': 'window_r',
  '22,0': 'vent',
  // desks, north wall
  '2,6': 'pinboard',
  '4,6': 'clock',
  '6,6': 'poster',
  '8,6': 'extinguisher',
  // break room, north wall
  '15,6': 'sign_kitchen',
  '16,6': 'menu_l',
  '17,6': 'menu_r',
  '21,6': 'shelf_mugs',
  '22,6': 'vent',
  // reception, north wall
  '2,12': 'extinguisher',
  '7,12': 'logo_l',
  '8,12': 'logo_m',
  '9,12': 'logo_r',
  '15,12': 'clock',
  '17,12': 'poster',
  '19,12': 'pinboard',
  '21,12': 'vent',
}

function isWall(g: string) {
  return g === '#'
}

function isWalkable(g: string) {
  return g === '.' || g === 'D' || /[1-4]/.test(g)
}

/** Wall autotile mask: bit set when that neighbour is open (not wall). N=1 E=2 S=4 W=8. */
export function wallMask(tx: number, ty: number): number {
  return (
    (isWall(glyphAt(tx, ty - 1)) ? 0 : 1) |
    (isWall(glyphAt(tx + 1, ty)) ? 0 : 2) |
    (isWall(glyphAt(tx, ty + 1)) ? 0 : 4) |
    (isWall(glyphAt(tx - 1, ty)) ? 0 : 8)
  )
}

/** A wall shows its plaster face when the tile south of it is open. */
export function wallShowsFace(tx: number, ty: number): boolean {
  return (wallMask(tx, ty) & 4) !== 0
}

function rugPart(x: number, y: number): TileName | null {
  for (const r of RUGS) {
    if (x < r.x0 || x > r.x1 || y < r.y0 || y > r.y1) continue
    const v = y === r.y0 ? 't' : y === r.y1 ? 'b' : ''
    const h = r.x0 === r.x1 ? 'lr' : x === r.x0 ? 'l' : x === r.x1 ? 'r' : ''
    const part = `${v}${h}` || 'c'
    return `rug_${r.kind}_${part}` as TileName
  }
  return null
}

/** Doorway frame for a `D` tile: stacked openings in the x=10 / x=14 walls
 *  read as one retracted glass partition; the single door at (5,12) sits in a
 *  horizontal wall and gets a header. */
export function doorSprite(tx: number, ty: number): TileName {
  const n = isWall(glyphAt(tx, ty - 1))
  const s = isWall(glyphAt(tx, ty + 1))
  const w = isWall(glyphAt(tx - 1, ty))
  const e = isWall(glyphAt(tx + 1, ty))
  if ((w || e) && !n && !s) return 'door_h'
  if (n) return 'door_v_top'
  if (s) return 'door_v_bot'
  return 'door_v_mid'
}

export function floorSprites(tx: number, ty: number): Sprite[] {
  const g = glyphAt(tx, ty)
  const out: Sprite[] = []
  if (isWall(g) || g === 'X') {
    out.push({ name: `wall_${wallMask(tx, ty)}` as TileName })
    if (g === 'X') out.push({ name: 'street_exit' })
    const decor = WALL_DECOR[`${tx},${ty}`]
    if (decor && wallShowsFace(tx, ty)) out.push({ name: decor })
    return out
  }
  out.push({ name: rugPart(tx, ty) ?? FLOOR_FOR_ZONE[zoneAt(tx, ty)] })
  if (isWall(glyphAt(tx, ty - 1))) out.push({ name: 'shade_n' })
  if (isWall(glyphAt(tx - 1, ty))) out.push({ name: 'shade_w' })
  if (g === 'D') out.push({ name: doorSprite(tx, ty) })
  return out
}

/** The static floor pass for the whole map. */
export function floorCells(): FloorCell[] {
  const cells: FloorCell[] = []
  for (let y = 0; y < MAP_HEIGHT; y++) {
    for (let x = 0; x < MAP_WIDTH; x++) cells.push({ x, y, layers: floorSprites(x, y) })
  }
  return cells
}

const isTable = (g: string) => g === 'T' || g === 'A'

export function propSprite(tx: number, ty: number, s: TileStates): Sprite | null {
  const g = glyphAt(tx, ty)
  switch (g) {
    case '=': {
      const left = glyphAt(tx - 1, ty) === '='
      const right = glyphAt(tx + 1, ty) === '='
      const part = left && right ? 'm' : left ? 'r' : 'l'
      if (ty === 15) return { name: `rdesk_${part}` as TileName }
      if (part === 'r') return { name: 'desk_r' }
      return { name: `desk_${part}_0` as TileName, frames: 2, periodMs: 2600 }
    }
    case 'c': {
      const north = glyphAt(tx, ty - 1)
      return { name: north === '=' || isTable(north) ? 'chair_n' : 'chair_s' }
    }
    case 'P':
      if (s.printer === 'printing') return { name: 'printer_printing_0', frames: 2, periodMs: 700 }
      return { name: s.printer === 'error' ? 'printer_error' : 'printer_working' }
    case 'S':
      return { name: s.cabinetOpen ? 'cabinet_open' : 'cabinet_closed' }
    case 'K': {
      const left = glyphAt(tx - 1, ty) === 'K'
      const right = glyphAt(tx + 1, ty) === 'K'
      if (!left) {
        return s.counterSteaming
          ? { name: 'counter_steam_0', frames: 2, periodMs: 1000 }
          : { name: 'counter_machine' }
      }
      return { name: right ? 'counter_cups' : 'counter_sink' }
    }
    case 'V':
      return s.vendingLit
        ? { name: 'vending_lit_0', frames: 2, periodMs: 640 }
        : { name: 'vending_idle' }
    case 't':
      return { name: glyphAt(tx - 1, ty) === 't' ? 'btable_r' : 'btable_l' }
    case 'T':
    case 'A': {
      const top = !isTable(glyphAt(tx, ty - 1))
      const left = !isTable(glyphAt(tx - 1, ty))
      const right = !isTable(glyphAt(tx + 1, ty))
      const part = `${top ? 't' : 'b'}${left ? 'l' : right ? 'r' : ''}`
      if (g === 'A' && part === 'tl') return { name: 'mtable_tl_agenda' }
      return { name: `mtable_${part}` as TileName }
    }
    case 'H':
      return { name: 'handout_rack' }
    case 'w':
      return { name: 'water_cooler' }
    case 'i':
      return { name: 'directory' }
    case 'p':
      return { name: (tx + ty) % 2 ? 'plant_b' : 'plant_a' }
    case 'E': {
      const side = glyphAt(tx - 1, ty) === 'E' ? 'r' : 'l'
      return { name: `elev_${side}_${s.elevatorOpen ? 'open' : 'closed'}` as TileName }
    }
    case 'R':
      return {
        name: s.readerGreen ? 'reader_green_0' : 'reader_red_0',
        frames: 2,
        periodMs: 1300,
      }
    default:
      return null
  }
}

/** Every prop on the floor for the given states. */
export function propCells(s: TileStates): PropCell[] {
  const cells: PropCell[] = []
  for (let y = 0; y < MAP_HEIGHT; y++) {
    for (let x = 0; x < MAP_WIDTH; x++) {
      const sprite = propSprite(x, y, s)
      if (sprite) cells.push({ x, y, sprite })
    }
  }
  return cells
}

/** Sheet offset for an atlas cell, as CSS background-position values. */
export function atlasOffset(name: TileName): { bx: number; by: number } {
  const [col, row] = TILE_ATLAS[name]
  return { bx: -col * 32, by: -row * 48 }
}

/** Props and actors share one z range so tall furniture occludes by row. */
export function rowZ(ty: number, actor = false): number {
  return 10 + ty * 2 + (actor ? 1 : 0)
}

export { isWalkable }
