import type { CapacitorConfig } from '@capacitor/cli'

/**
 * Frame black — the one boot color. It is `--cc-bg` in `src/ui/tokens.css`,
 * the surface the ladder sits on in `index.html`'s `.boot-splash` and in the
 * Stage card, so a cold launch is one unbroken black from the LaunchScreen
 * storyboard through the SplashScreen plugin, the WKWebView background,
 * `html/body/#root`, `.boot-splash`, and the React preloader.
 *
 * Keep in step with BOOT_COLOR in `src/platform/native.ts`, the inline
 * `<style>` + `theme-color` in `index.html`, and
 * `public/manifest.webmanifest`. `src/__tests__/boot-splash.test.ts` fails
 * if any link in the chain drifts. See docs/ios-capacitor-plan.md §2.7.
 */
const BOOT_COLOR = '#06080c'

// Portrait orientation is Xcode-only (UISupportedInterfaceOrientations on the
// iOS target). Capacitor config cannot lock it; set it after `npx cap add ios`.
const config: CapacitorConfig = {
  appId: 'com.corporateclimb.app',
  appName: 'Corporate Climb',
  webDir: 'dist',
  // WKWebView background — visible only in the gap between the native splash
  // fading out and the first HTML paint. Same black, so there is no gap to see.
  backgroundColor: BOOT_COLOR,
  ios: {
    // The WebView is full-bleed under the status bar and home indicator;
    // `index.html` pads `#root` with env(safe-area-inset-*) itself. Any other
    // value here makes UIKit inset the scroll view as well and the app
    // double-insets (a blank band under the bar).
    contentInset: 'never',
  },
  plugins: {
    SplashScreen: {
      // Native splash art is `resources/splash.png` (see resources/README.md;
      // generated by `node scripts/gen-splash.mjs`). It mirrors `.boot-splash`
      // so the plugin's 200 ms fade lands on identical art.
      launchAutoHide: true,
      backgroundColor: BOOT_COLOR,
      showSpinner: false,
    },
    StatusBar: {
      // Style.Dark = light text on a dark bar, sitting over frame black.
      style: 'DARK',
      // Overlay: the bar is transparent and the WebView draws underneath it;
      // safe-area padding in index.html keeps the game clear of the glyphs.
      // (With overlay off the plugin shrinks the WebView and paints this
      // backgroundColor behind the bar instead — same black either way.)
      overlaysWebView: true,
      backgroundColor: BOOT_COLOR,
    },
  },
}

export default config
