// Generated by scripts/gen_office_icons.py — do not edit by hand.
// Cell = 16×16 art in an 18×18 slot (1px transparent gutter). Keys are
// perk / Status Symbol ids plus `locked`; PixelIcon reads them.

export const ICON_SHEET_URL = '/office/icons.png'
export const ICON_CELL = 16
export const ICON_PAD = 1
export const ICON_STRIDE = 18
export const ICON_SHEET_W = 144
export const ICON_SHEET_H = 72

export const ICON_ATLAS = {
  gym_membership: [0, 0],
  assertiveness_training: [1, 0],
  executive_presence: [2, 0],
  balanced_package: [3, 0],
  overtime_grind: [4, 0],
  perfectionist: [5, 0],
  networking_guru: [6, 0],
  morning_person: [7, 0],
  self_care: [0, 1],
  negotiator: [1, 1],
  employee_discount: [2, 1],
  headhunter: [3, 1],
  signing_bonus: [4, 1],
  personal_brand: [5, 1],
  golden_handcuffs: [6, 1],
  killer_instinct: [7, 1],
  dividends: [0, 2],
  golden_stapler: [1, 2],
  corner_office_key: [2, 2],
  executive_parking: [3, 2],
  platinum_card: [4, 2],
  ergonomic_throne: [5, 2],
  lucky_tie: [6, 2],
  stress_ball: [7, 2],
  mahogany_desk: [0, 3],
  ceo_signature: [1, 3],
  campus_keycard: [2, 3],
  trophy_shelf: [3, 3],
  locked: [4, 3],
} as const satisfies Record<string, readonly [number, number]>

export type IconName = keyof typeof ICON_ATLAS
