import type { CSSProperties, HTMLAttributes } from 'react'
import {
  ICON_ATLAS,
  ICON_CELL,
  ICON_PAD,
  ICON_SHEET_H,
  ICON_SHEET_URL,
  ICON_SHEET_W,
  ICON_STRIDE,
  type IconName,
} from './iconAtlas'
import styles from './PixelIcon.module.css'

export type { IconName }

/** Integer multiples of the 16px cell so the art never lands on a half pixel. */
export type PixelIconScale = 1 | 2 | 3

export function hasPixelIcon(name: string): name is IconName {
  return Object.prototype.hasOwnProperty.call(ICON_ATLAS, name)
}

/**
 * One cell of the Codex icon sheet (`public/office/icons.png`, regenerated by
 * `scripts/gen_office_icons.py`). Sized and positioned through custom
 * properties so the module CSS owns the rendering; the sheet is painted as
 * a background so a missing image degrades to an empty slot, never alt text.
 */
export default function PixelIcon({
  name,
  scale = 2,
  className,
  style,
  ...rest
}: {
  name: IconName
  scale?: PixelIconScale
} & HTMLAttributes<HTMLSpanElement>) {
  const [col, row] = ICON_ATLAS[name]
  const vars = {
    '--pi-size': `${ICON_CELL * scale}px`,
    '--pi-sheet-w': `${ICON_SHEET_W * scale}px`,
    '--pi-sheet-h': `${ICON_SHEET_H * scale}px`,
    '--pi-x': `${-(ICON_PAD + col * ICON_STRIDE) * scale}px`,
    '--pi-y': `${-(ICON_PAD + row * ICON_STRIDE) * scale}px`,
    '--pi-url': `url(${ICON_SHEET_URL})`,
    ...style,
  } as CSSProperties
  return (
    <span
      className={[styles.icon, className].filter(Boolean).join(' ')}
      style={vars}
      data-icon={name}
      aria-hidden="true"
      {...rest}
    />
  )
}
