import type { Enemy, PlayerClass } from '@/types'
import type { CoworkerId, EncounterId } from './ids'

export const OFFICE_ENCOUNTERS: Record<
  EncounterId,
  Enemy & {
    rank: number
    boss: boolean
    recruit: CoworkerId | null
    xp: number
    options: number
    declinable: boolean
    titleCard: string
    eyebrow?: string
  }
> = {
  enc_desk_challenger: {
    floor: 0,
    rank: 0,
    name: 'Gavin',
    emoji: '📎',
    spriteId: 'overachiever',
    maxHp: 70,
    atk: 8,
    def: 6,
    types: ['normal'],
    title: 'THE DESK NEIGHBOR',
    titleCard: 'DESK-PIT ARGUMENT',
    taunt: 'You fixed the printer. Fix this.',
    defeat: 'Gavin returns to his desk and types nothing, loudly.',
    boss: false,
    recruit: 'cw_desk_challenger',
    xp: 15,
    options: 8,
    declinable: true,
    moves: [
      { name: 'Well, Actually', dmg: 10, type: 'normal' },
      {
        name: 'Passive-Aggressive Sticky Note',
        dmg: 12,
        type: 'influence',
        status: { id: 'demoralized', target: 'enemy', chance: 0.3 },
      },
    ],
  },
  enc_meeting_prepper: {
    floor: 1,
    rank: 1,
    name: 'Priya',
    emoji: '📅',
    spriteId: 'scrum',
    maxHp: 85,
    atk: 11,
    def: 7,
    types: ['strategy'],
    title: 'THE MEETING COORDINATOR',
    titleCard: 'PRE-MEETING SPAR',
    taunt: "I've blocked fifteen minutes for this.",
    defeat: 'Priya ends the meeting four minutes early. Unheard of.',
    boss: false,
    recruit: 'cw_meeting_prepper',
    xp: 22,
    options: 11,
    declinable: true,
    moves: [
      {
        name: 'Calendar Hold',
        dmg: 12,
        type: 'strategy',
        status: { id: 'micromanaged', target: 'enemy', chance: 0.4 },
      },
      { name: 'Agenda Item', dmg: 14, type: 'strategy' },
      { name: 'Circle Back', dmg: 8, type: 'influence', heal: 10 },
    ],
  },
  enc_supervisor_1on1: {
    floor: 2,
    rank: 2,
    name: 'Holloway',
    emoji: '📋',
    spriteId: 'manager',
    maxHp: 130,
    atk: 14,
    def: 9,
    types: ['influence', 'strategy'],
    title: 'THE TEAM LEAD (INTERIM)',
    titleCard: 'ONE-ON-ONE',
    eyebrow: 'NO LEAVING EARLY',
    taunt: "There's no leaving early.",
    defeat: 'Holloway writes something in a notebook. Probably your name. Possibly a smiley.',
    boss: true,
    recruit: null,
    xp: 30,
    options: 20,
    declinable: false,
    moves: [
      {
        name: 'One-on-One',
        dmg: 14,
        type: 'influence',
        status: { id: 'demoralized', target: 'enemy', chance: 0.4 },
      },
      { name: 'Stretch Goal', dmg: 18, type: 'execution' },
      {
        name: "Let's Take This Offline",
        dmg: 10,
        type: 'strategy',
        heal: 12,
        status: { id: 'motivated', target: 'self' },
      },
    ],
  },
  // ── Floor 2 (docs/rpg/floor-2-design.md §5) ──
  enc_help_desk_intern: {
    floor: 3,
    rank: 3,
    name: 'Teddy',
    emoji: '🎧',
    spriteId: 'intern',
    maxHp: 95,
    atk: 12,
    def: 8,
    types: ['technical'],
    title: 'THE ROTATIONAL INTERN',
    titleCard: 'COMPLIANCE TRAINING',
    eyebrow: 'MODULE 1 OF 1',
    taunt: "Please hold. You're my only ticket.",
    defeat: 'Teddy closes the ticket, reopens it to add a note, and closes it again.',
    boss: false,
    recruit: 'cw_help_desk_intern',
    xp: 36,
    options: 15,
    declinable: true,
    moves: [
      { name: 'Have You Tried Restarting', dmg: 12, type: 'technical', heal: 8 },
      {
        name: 'Reply All',
        dmg: 10,
        type: 'influence',
        status: { id: 'burned_out', target: 'enemy', chance: 0.3 },
      },
      { name: 'Escalate', dmg: 15, type: 'technical' },
    ],
  },
  enc_auditor: {
    floor: 4,
    rank: 4,
    name: 'Whitlock',
    emoji: '🧾',
    spriteId: 'boss',
    maxHp: 120,
    atk: 14,
    def: 10,
    types: ['analytics'],
    title: 'THE EXTERNAL AUDITOR',
    titleCard: 'THE AUDIT',
    eyebrow: 'RECEIPTS, PLEASE',
    taunt: 'Every receipt. Every quarter. Every one of you.',
    defeat: 'Whitlock initials the ledger. Once. In pencil.',
    boss: false,
    recruit: null,
    xp: 43,
    options: 21,
    declinable: true,
    moves: [
      { name: 'Line Item', dmg: 14, type: 'analytics' },
      {
        name: 'Discrepancy',
        dmg: 18,
        type: 'analytics',
        status: { id: 'micromanaged', target: 'enemy', chance: 0.4 },
      },
      { name: 'Reconcile', dmg: 8, type: 'analytics', heal: 14 },
    ],
  },
  enc_director_review: {
    floor: 5,
    rank: 5,
    name: 'Kessler',
    emoji: '🗂️',
    spriteId: 'vp',
    maxHp: 170,
    atk: 16,
    def: 12,
    types: ['execution', 'analytics'],
    title: 'THE DIRECTOR OF OPERATIONS',
    titleCard: 'OPERATIONS REVIEW',
    eyebrow: 'NO RESCHEDULING',
    taunt: "There's no rescheduling.",
    defeat: "Kessler uncrosses his arms. It takes a moment; they've been like that since March.",
    boss: true,
    recruit: null,
    xp: 55,
    options: 32,
    declinable: false,
    moves: [
      {
        name: 'Process Improvement',
        dmg: 15,
        type: 'execution',
        status: { id: 'micromanaged', target: 'enemy', chance: 0.4 },
      },
      { name: 'KPI Review', dmg: 19, type: 'analytics' },
      {
        name: 'Headcount Freeze',
        dmg: 11,
        type: 'analytics',
        status: { id: 'demoralized', target: 'enemy', chance: 0.5 },
      },
    ],
    // Fires at ≤ 50% of phase-1 HP once turn.ts un-gates phase 2 for encounters
    // (docs/rpg/floor-2-engine-hooks.md §5). Until then it is inert content.
    phase2: {
      name: 'Kessler (Restructuring)',
      maxHp: 100,
      atk: 18,
      def: 10,
      types: ['strategy', 'execution'],
      taunt: "Let's restructure.",
      moves: [
        { name: 'Restructure', dmg: 20, type: 'strategy' },
        { name: 'Right-Size', dmg: 26, type: 'execution', acc: 85 },
        {
          name: 'Synergy',
          dmg: 12,
          type: 'influence',
          heal: 16,
          status: { id: 'motivated', target: 'self' },
        },
      ],
    },
  },
}

const NONE_PERK = { name: 'None', desc: '', icon: '' }

export const COWORKER_KITS: Record<CoworkerId, PlayerClass> = {
  cw_desk_challenger: {
    id: 'pm',
    name: 'Gavin',
    emoji: '📎',
    spriteId: 'overachiever',
    maxHp: 70,
    atk: 10,
    def: 8,
    spd: 10,
    types: ['normal'],
    desc: 'Senior Associate. Corrects you. Loudly.',
    perk: NONE_PERK,
    moves: [
      {
        name: 'Well, Actually',
        dmg: 10,
        type: 'normal',
        desc: 'Corrects you. Loudly.',
        pp: 20,
      },
      {
        name: 'Passive-Aggressive Sticky Note',
        dmg: 12,
        type: 'influence',
        desc: "Left on the monitor. Signed 'thx'.",
        pp: 10,
        status: { id: 'demoralized', target: 'enemy', chance: 0.4 },
      },
    ],
  },
  cw_meeting_prepper: {
    id: 'pm',
    name: 'Priya',
    emoji: '📅',
    spriteId: 'scrum',
    maxHp: 80,
    atk: 11,
    def: 9,
    spd: 10,
    types: ['strategy'],
    desc: 'Ops. Front-loads the calendar.',
    perk: NONE_PERK,
    moves: [
      {
        name: 'Calendar Hold',
        dmg: 12,
        type: 'strategy',
        desc: 'Blocks their afternoon.',
        pp: 12,
        status: { id: 'micromanaged', target: 'enemy', chance: 0.5 },
      },
      {
        name: 'Agenda Item',
        dmg: 14,
        type: 'strategy',
        desc: 'Item 4 is you.',
        pp: 15,
      },
      {
        name: 'Circle Back',
        dmg: 8,
        type: 'influence',
        desc: 'Reschedules the damage.',
        pp: 8,
        heal: 10,
      },
    ],
  },
  cw_help_desk_intern: {
    id: 'eng',
    name: 'Teddy',
    emoji: '🎧',
    spriteId: 'intern',
    maxHp: 75,
    atk: 9,
    def: 10,
    spd: 10,
    types: ['technical'],
    desc: 'Rotational intern. Month fourteen.',
    perk: NONE_PERK,
    moves: [
      {
        name: 'Have You Tried Restarting',
        dmg: 11,
        type: 'technical',
        desc: 'Turns it off and on. Including you.',
        pp: 15,
        heal: 6,
      },
      {
        name: 'Reply All',
        dmg: 9,
        type: 'influence',
        desc: "Per my last email. Everyone's.",
        pp: 12,
        status: { id: 'burned_out', target: 'enemy', chance: 0.4 },
      },
      {
        name: 'Escalate',
        dmg: 14,
        type: 'technical',
        desc: "Now it's someone else's problem.",
        pp: 10,
      },
    ],
  },
}

export const COWORKER_NAME: Record<CoworkerId, string> = {
  cw_desk_challenger: 'Gavin',
  cw_meeting_prepper: 'Priya',
  cw_help_desk_intern: 'Teddy',
}
