#!/usr/bin/env python3
"""Codex icon family — hand-authored 16×16 pixel glyphs, one sheet.

Output: public/office/icons.png (RGBA) plus src/ui/iconAtlas.ts, the
name → cell index that `PixelIcon` reads. One cell per perk and Status
Symbol (keyed by content id) plus `locked`, the glyph every gated slot
shows before its achievement is earned.

The art language is the Office one (scripts/gen_office_actors.py,
scripts/gen_office_tiles.py): light from the top-left, a lit / base /
shadow ramp per material, one plum ink for the silhouette, no
anti-aliasing, no gradients. Every glyph is an object — a dumbbell, a
shield, a key — never a face or a figure, so the set reads as one family
on the Codex slot and nothing in it is a portrait.

Templates are 16 rows × 16 columns of palette letters ('.' transparent).
The body is drawn inside the 14×14 interior; the generator inks the
4-neighbour outline into the outer ring and refuses a template whose
outline would leave the cell.

Cells are stored on an 18px stride with a 1px transparent gutter so a
scaled `background-position` never samples the neighbouring glyph.

Usage:
    python3 scripts/gen_office_icons.py            # write sheet + atlas
    python3 scripts/gen_office_icons.py --preview  # also dump a 4× contact sheet to /tmp
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

CELL = 16
PAD = 1
STRIDE = CELL + 2 * PAD
COLS = 8

ROOT = Path(__file__).resolve().parents[1]
OUT_PNG = ROOT / 'public' / 'office' / 'icons.png'
OUT_TS = ROOT / 'src' / 'ui' / 'iconAtlas.ts'

RGBA = tuple[int, int, int, int]


def hexc(value: str, a: int = 255) -> RGBA:
    v = value.lstrip('#')
    return int(v[0:2], 16), int(v[2:4], 16), int(v[4:6], 16), a


# ---------------------------------------------------------------------------
# Palette — the tileset's material ramps, one letter per swatch.
# Uppercase = lit, lowercase = base, third letter = shadow.
# ---------------------------------------------------------------------------

INK = hexc('#1b1726')

PALETTE: dict[str, RGBA] = {
    'O': INK,
    # gold
    'G': hexc('#ffe082'),
    'g': hexc('#ffc107'),
    'd': hexc('#b8860b'),
    # steel
    'S': hexc('#c2cbd6'),
    's': hexc('#9ca7b6'),
    't': hexc('#6b7686'),
    # paper
    'P': hexc('#ffffff'),
    'p': hexc('#f2f4f6'),
    'q': hexc('#c5ccd6'),
    # red
    'x': hexc('#ff8a80'),
    'r': hexc('#ff5a5a'),
    'R': hexc('#b83a3a'),
    # green
    'e': hexc('#4ade80'),
    'E': hexc('#2d9c58'),
    # navy fabric
    'N': hexc('#2c3d68'),
    'n': hexc('#1e2a4a'),
    'j': hexc('#141c33'),
    # wood
    'W': hexc('#a97a4c'),
    'w': hexc('#8a5f3b'),
    'v': hexc('#65452a'),
    # laminate / cardboard
    'L': hexc('#dcb883'),
    'l': hexc('#c6a06d'),
    'k': hexc('#a68352'),
    # dark plastic
    'B': hexc('#45506a'),
    'b': hexc('#2f3646'),
    'c': hexc('#232838'),
    # water / glass
    'A': hexc('#bdeaff'),
    'a': hexc('#5fc3f0'),
    # leaf
    'F': hexc('#6cc084'),
    'f': hexc('#3f9160'),
    'h': hexc('#2b6a45'),
    # signage blue
    'U': hexc('#6a95e8'),
    'u': hexc('#3b6fd8'),
    'V': hexc('#2a4fa0'),
    # yellow (stress ball)
    'Y': hexc('#ffe27a'),
    'y': hexc('#f2c14e'),
    'Q': hexc('#c49a2c'),
    # locked grey
    'Z': hexc('#655f6e'),
    'z': hexc('#4a4553'),
    'M': hexc('#2c3142'),
}


def rows(block: str) -> list[str]:
    out = [ln.strip() for ln in block.strip('\n').splitlines()]
    return [ln for ln in out if ln]


# ---------------------------------------------------------------------------
# Glyphs — keyed by perk / relic id. Order here is sheet order.
# ---------------------------------------------------------------------------

ICONS: dict[str, list[str]] = {}


def icon(name: str, block: str) -> None:
    tpl = rows(block)
    if len(tpl) != CELL or any(len(ln) != CELL for ln in tpl):
        raise SystemExit(f'{name}: template must be {CELL}×{CELL}')
    bad = {ch for ln in tpl for ch in ln if ch != '.' and ch not in PALETTE}
    if bad:
        raise SystemExit(f'{name}: unknown palette letters {sorted(bad)}')
    ICONS[name] = tpl


# ── Perks: stat packages ────────────────────────────────────────────────────

# Gym Membership — dumbbell
icon(
    'gym_membership',
    """
    ................
    ................
    ................
    .SS.........SS..
    .Ss.........Ss..
    .SsSS.....SSSs..
    .SsSsSSSSSsstSs.
    .SsSssssssstSs..
    .SsSstttttstSs..
    .Sstt.....ttSs..
    .Ss.........Ss..
    .tt.........tt..
    ................
    ................
    ................
    ................
    """,
)

# Assertiveness Training — speech bubble, exclamation
icon(
    'assertiveness_training',
    """
    ................
    ................
    ...PPPPPPPPPP...
    ..Pppppppppppq..
    ..Pppppprrppppq.
    ..Pppppprrppppq.
    ..Pppppprrppppq.
    ..Pppppprrppppq.
    ..Pppppppppppq..
    ..Pppppprrppppq.
    ..qqqqqqqqqqqq..
    ...qq...........
    ...q............
    ................
    ................
    ................
    """,
)

# Executive Presence — shield with a gold band (no portrait)
icon(
    'executive_presence',
    """
    ................
    ................
    ..SSSSSSSSSSSS..
    ..Sssssssssst...
    ..Sssssssssst...
    ..SGGGGGGGGGt...
    ..Sgggggggggt...
    ..Sdddddddddt...
    ..Sssssssssst...
    ...Sssssssst....
    ....Sssssst.....
    .....Sssst......
    ......Sst.......
    .......St.......
    ................
    ................
    """,
)

# Total Comp Package — taped cardboard box
icon(
    'balanced_package',
    """
    ................
    ................
    ................
    ..LLLLLLLLLLLL..
    ..Llllllpplllk..
    ..Llllllpplllk..
    ..OOOOOOppOOOO..
    ..Llllllpplllk..
    ..Llllllpplllk..
    ..Llllllpplllk..
    ..Llllllpplllk..
    ..Llllllpplllk..
    ..kkkkkkqqkkkk..
    ................
    ................
    ................
    """,
)

# ── Perks: passives ─────────────────────────────────────────────────────────

# Overtime Grind — crescent moon and one star
icon(
    'overtime_grind',
    """
    ................
    ................
    ......GGGG......
    ....GGgg........
    ...Gggg....G....
    ..Ggggg...GGG...
    ..Ggggg....G....
    ..Ggggg.........
    ..Ggggg.........
    ..ggggg.........
    ...gggd.........
    ....dddd........
    ......dddd......
    ................
    ................
    ................
    """,
)

# Perfectionist — magnifying glass
icon(
    'perfectionist',
    """
    ................
    ................
    ....SSSS........
    ...SAAaas.......
    ..SAaaaaas......
    ..Saaaaaas......
    ..Saaaaaas......
    ..saaaaaat......
    ...saaaat.......
    ....tttt.Bb.....
    ..........Bb....
    ...........Bb...
    ............Bb..
    .............b..
    ................
    ................
    """,
)

# Networking Guru — three nodes, wired
icon(
    'networking_guru',
    """
    ................
    ................
    ......GGG.......
    ......Ggd.......
    ......ddd.......
    .....s...s......
    ....s.....s.....
    ....s.....s.....
    ...s.......s....
    ...s.......s....
    ..GGG.....GGG...
    ..GgdsssssGgd...
    ..ddd.....ddd...
    ................
    ................
    ................
    """,
)

# Morning Person — sunrise over the hills
icon(
    'morning_person',
    """
    ................
    ................
    .......GG.......
    ...G...GG...G...
    ....G......G....
    ......GGGG......
    .....GGgggg.....
    .GG..Gggggg..GG.
    .....Gggggg.....
    .....gggggg.....
    .FFFFFFFFFFFFFF.
    .ffffffffffffff.
    .hhhhhhhhhhhhhh.
    ................
    ................
    ................
    """,
)

# Self Care — heart
icon(
    'self_care',
    """
    ................
    ................
    ................
    ...rrr...rrr....
    ..rPrrr.rrrrr...
    ..rPrrrrrrrrr...
    ..rrrrrrrrrrr...
    ..rrrrrrrrrrR...
    ...rrrrrrrrR....
    ....rrrrrrR.....
    .....rrrrR......
    ......rrR.......
    .......R........
    ................
    ................
    ................
    """,
)

# ── Perks: economy ──────────────────────────────────────────────────────────

# Negotiator — chart climbing off the axes
icon(
    'negotiator',
    """
    ................
    ................
    ..s.............
    ..s.......eee...
    ..s.........e...
    ..s........ee...
    ..s.......e.....
    ..s......e......
    ..s.....e.......
    ..s..e.e........
    ..s.e.e.........
    ..se............
    ..ssssssssssss..
    ................
    ................
    ................
    """,
)

# Employee Discount — price tag with a red band
icon(
    'employee_discount',
    """
    ................
    ................
    ................
    ................
    ....GGGGGGGGGG..
    ....Ggggggrrd...
    ...GgOggggrrd...
    ..GggOggggrrd...
    ..Gggggggggrrd..
    ...ggggggggrrd..
    ....gggggggrrd..
    ....dddddddddd..
    ................
    ................
    ................
    ................
    """,
)

# Headhunter Contact — telephone handset
icon(
    'headhunter',
    """
    ................
    ................
    ................
    ................
    ..BBB......BBB..
    ..BbbBBBBBBbbc..
    ..Bbbbbbbbbbbc..
    ..Bbbccccccbbc..
    ..Bbbc....Bbbc..
    ..Bbbc....Bbbc..
    ..cccc....cccc..
    ................
    ................
    ................
    ................
    ................
    """,
)

# Signing Bonus — banknote
icon(
    'signing_bonus',
    """
    ................
    ................
    ................
    ................
    ..PPPPPPPPPPPP..
    ..PEEEEEEEEEEq..
    ..PEeeeeeeeeEq..
    ..PEeeeGGeeeEq..
    ..PEeeeGGeeeEq..
    ..PEeeeeeeeeEq..
    ..PEEEEEEEEEEq..
    ..qqqqqqqqqqqq..
    ................
    ................
    ................
    ................
    """,
)

# ── Perks: unlockable ───────────────────────────────────────────────────────

# Personal Brand — four-point star and two sparks
icon(
    'personal_brand',
    """
    ................
    ................
    .......G........
    .......G....G...
    ......GGG..GGG..
    ......GgG...G...
    .....GGgGG......
    ..GGGGgggGGGG...
    .....GGdGG......
    ...G..GdG.......
    ..GGG.ddd.......
    ...G...d........
    .......d........
    ................
    ................
    ................
    """,
)

# Golden Handcuffs — two interlocked links
icon(
    'golden_handcuffs',
    """
    ................
    ................
    ................
    ................
    ...GGGGG........
    ..g.....g.......
    ..g.....g.......
    ..g.....GGGGG...
    ..g....gd....g..
    ...ddddg.....g..
    .......g.....g..
    .......g.....d..
    ........ddddd...
    ................
    ................
    ................
    """,
)

# Killer Instinct — fin above the water
icon(
    'killer_instinct',
    """
    ................
    ................
    ................
    ........s.......
    .......ss.......
    ......Sss.......
    .....Ssss.......
    ....Sssss.......
    ...Sssssst......
    ..Sssssssst.....
    .AAaAAAaAAAaAAA.
    .aaaaaaaaaaaaaa.
    .aaaaaaaaaaaaaa.
    ................
    ................
    ................
    """,
)

# Dividends — coin stack
icon(
    'dividends',
    """
    ................
    ................
    ................
    ................
    ....GGGGGGGG....
    ...GPgggggggd...
    ...dddddddddd...
    ...GGgggggggd...
    ...dddddddddd...
    ...GGgggggggd...
    ...dddddddddd...
    ................
    ................
    ................
    ................
    ................
    """,
)

# ── Status Symbols ──────────────────────────────────────────────────────────

# Golden Stapler — side view, arm raised
icon(
    'golden_stapler',
    """
    ................
    ................
    ................
    ................
    ..........GGG...
    ......GGGGggg...
    ..GGGGggggggd...
    ..Gggggggggggd..
    ..dddddddddddd..
    ...Bbbbbbbbbbb..
    ..Bbbbbbbbbbbc..
    ..cccccccccccc..
    ................
    ................
    ................
    ................
    """,
)

# Corner Office Key — bow left, teeth down
icon(
    'corner_office_key',
    """
    ................
    ................
    ................
    ................
    ..GGGG..........
    .G....G.........
    .G....G.........
    .G....GGGGGGGG..
    .g....gggggggg..
    .g....d..dd..d..
    ..dddd...dd..d..
    ................
    ................
    ................
    ................
    ................
    """,
)

# Executive Parking Spot — P sign on a post
icon(
    'executive_parking',
    """
    ................
    ................
    ...UUUUUUUUUU...
    ...UuuPPPuuuV...
    ...UuuPuuPuuV...
    ...UuuPuuPuuV...
    ...UuuPPPuuuV...
    ...UuuPuuuuuV...
    ...UuuPuuuuuV...
    ...UuuPuuuuuV...
    ...UuuuuuuuuV...
    ...VVVVVVVVVV...
    .......Ss.......
    .......ss.......
    ................
    ................
    """,
)

# Platinum Corporate Card — stripe and chip
icon(
    'platinum_card',
    """
    ................
    ................
    ................
    ................
    ..SSSSSSSSSSSS..
    ..Ssssssssssst..
    ..Scccccccccct..
    ..Scccccccccct..
    ..Ssssssssssst..
    ..SsGGssssssst..
    ..Ssddssssssst..
    ..tttttttttttt..
    ................
    ................
    ................
    ................
    """,
)

# Ergonomic Throne — task chair
icon(
    'ergonomic_throne',
    """
    ................
    ................
    ....NNNNNNNNN...
    ....Nnnnnnnnj...
    ....Nnnnnnnnj...
    ....Nnnnnnnnj...
    ....Nnnnnnnnj...
    ....jjjjjjjjj...
    ..NNNNNNNNNNNN..
    ..jjjjjjjjjjjj..
    .......Ss.......
    .......Ss.......
    ...ssssSsssss...
    ..t.........t...
    ................
    ................
    """,
)

# Lucky Tie — knot, blade, one gold stripe
icon(
    'lucky_tie',
    """
    ................
    ................
    ......xrrR......
    ......xrrR......
    .......rr.......
    .......rr.......
    ......xrrR......
    ......xrrR......
    ......xGgR......
    .....xrrrrR.....
    .....xrrrrR.....
    .....xrrrrR.....
    ......xrrR......
    .......rR.......
    ................
    ................
    """,
)

# Stress Ball — squeezed
icon(
    'stress_ball',
    """
    ................
    ................
    ................
    .....YYYYyy.....
    ....YYyyyyyy....
    ...Yyyyyyyyyy...
    ...YyyyQQQQyy...
    ...Yyyyyyyyyy...
    ...YyQQQQyyyQ...
    ...yyyyyyyyyQ...
    ...yyyyyyyyQQ...
    ....yyyyQQQQ....
    .....QQQQQQ.....
    ................
    ................
    ................
    """,
)

# Mahogany Desk — slab on two pedestals
icon(
    'mahogany_desk',
    """
    ................
    ................
    ................
    ................
    .WWWWWWWWWWWWWW.
    .wwwwwwwwwwwwwv.
    .vvvvvvvvvvvvvv.
    ..Wwv......Wwv..
    ..Wgv......Wgv..
    ..Wwv......Wwv..
    ..Wgv......Wgv..
    ..Wwv......Wwv..
    ..vvv......vvv..
    ................
    ................
    ................
    """,
)

# CEO's Signature — fountain pen over a scrawl
icon(
    'ceo_signature',
    """
    ................
    ................
    .............BB.
    ............BBb.
    ...........BBb..
    ..........BBb...
    .........BBb....
    ........BBb.....
    .......BBb......
    ......BBb.......
    .....Bbb........
    ....Ggd.........
    ...Gd...ppp.pp..
    ..d....pp..pp.p.
    ................
    ................
    """,
)

# All-Campus Keycard — badge on a lanyard (colour band, no photo)
icon(
    'campus_keycard',
    """
    ................
    .......nn.......
    .......nn.......
    .......nn.......
    ......SSss......
    ....PPPPPPPP....
    ....Pppppppq....
    ....Puuuuuuq....
    ....Puuuuuuq....
    ....Pppppppq....
    ....Pqqqqqpq....
    ....Pppppppq....
    ....Pqqqpppq....
    ....qqqqqqqq....
    ................
    ................
    """,
)

# Trophy Shelf — cup on a plank
icon(
    'trophy_shelf',
    """
    ................
    ................
    ....GGGGGGG.....
    ..G.Ggggggd.G...
    ..G.Ggggggd.G...
    ..GGGgggggdGG...
    ....Ggggggd.....
    .....Ggggd......
    ......Ggd.......
    .......g........
    .......g........
    .....GGgggd.....
    ....dddddddd....
    .WWWWWWWWWWWWWW.
    .vvvvvvvvvvvvvv.
    ................
    """,
)

# ── Locked slot ─────────────────────────────────────────────────────────────

# Locked — padlock, muted
icon(
    'locked',
    """
    ................
    ................
    .....ZZZZZZ.....
    ....Z......Z....
    ....Z......Z....
    ....z......z....
    ....z......z....
    ...ZZZZZZZZZZ...
    ...ZzzzzzzzzM...
    ...ZzzzOOzzzM...
    ...ZzzzOOzzzM...
    ...ZzzzzOzzzM...
    ...ZzzzzzzzzM...
    ...MMMMMMMMMM...
    ................
    ................
    """,
)


# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------


def render(name: str, tpl: list[str]) -> Image.Image:
    im = Image.new('RGBA', (CELL, CELL), (0, 0, 0, 0))
    body: set[tuple[int, int]] = set()
    for y, ln in enumerate(tpl):
        for x, ch in enumerate(ln):
            if ch == '.':
                continue
            body.add((x, y))
            im.putpixel((x, y), PALETTE[ch])
    for x, y in body:
        for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
            if (nx, ny) in body:
                continue
            if not (0 <= nx < CELL and 0 <= ny < CELL):
                raise SystemExit(f'{name}: outline leaves the cell at ({nx}, {ny})')
            im.putpixel((nx, ny), INK)
    return im


def build_sheet() -> tuple[Image.Image, dict[str, tuple[int, int]]]:
    names = list(ICONS)
    nrows = (len(names) + COLS - 1) // COLS
    sheet = Image.new('RGBA', (COLS * STRIDE, nrows * STRIDE), (0, 0, 0, 0))
    index: dict[str, tuple[int, int]] = {}
    for i, name in enumerate(names):
        col, row = i % COLS, i // COLS
        sheet.alpha_composite(render(name, ICONS[name]), (col * STRIDE + PAD, row * STRIDE + PAD))
        index[name] = (col, row)
    return sheet, index


def emit_ts(index: dict[str, tuple[int, int]], sheet: Image.Image) -> str:
    lines = [
        '// Generated by scripts/gen_office_icons.py — do not edit by hand.',
        '// Cell = 16×16 art in an 18×18 slot (1px transparent gutter). Keys are',
        '// perk / Status Symbol ids plus `locked`; PixelIcon reads them.',
        '',
        "export const ICON_SHEET_URL = '/office/icons.png'",
        f'export const ICON_CELL = {CELL}',
        f'export const ICON_PAD = {PAD}',
        f'export const ICON_STRIDE = {STRIDE}',
        f'export const ICON_SHEET_W = {sheet.width}',
        f'export const ICON_SHEET_H = {sheet.height}',
        '',
        'export const ICON_ATLAS = {',
    ]
    for name, (col, row) in index.items():
        lines.append(f'  {name}: [{col}, {row}],')
    lines.append('} as const satisfies Record<string, readonly [number, number]>')
    lines.append('')
    lines.append('export type IconName = keyof typeof ICON_ATLAS')
    lines.append('')
    return '\n'.join(lines)


def main() -> None:
    sheet, index = build_sheet()
    OUT_PNG.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(OUT_PNG, optimize=True)
    OUT_TS.write_text(emit_ts(index, sheet))
    print(f'wrote {OUT_PNG.relative_to(ROOT)} ({sheet.width}×{sheet.height}, {len(index)} icons)')
    print(f'wrote {OUT_TS.relative_to(ROOT)}')
    if '--preview' in sys.argv:
        # Codex slot surface behind every cell so the ink outline reads as it will in-game.
        bg = Image.new('RGBA', sheet.size, (42, 48, 66, 255))
        bg.alpha_composite(sheet)
        big = bg.resize((sheet.width * 4, sheet.height * 4), Image.NEAREST)
        big.save('/tmp/office_icons_preview.png')
        print('wrote /tmp/office_icons_preview.png')


if __name__ == '__main__':
    main()
